#include "ppc.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <sstream>
#include <utility>

#include "pef.h"

namespace cyt {
namespace {

// Instruction field accessors, named after the architecture manual's fields.
inline u32 OPCD(u32 w) { return w >> 26; }
inline u32 rD(u32 w)   { return (w >> 21) & 31; }
inline u32 rS(u32 w)   { return (w >> 21) & 31; }
inline u32 rA(u32 w)   { return (w >> 16) & 31; }
inline u32 rB(u32 w)   { return (w >> 11) & 31; }
inline u32 rC(u32 w)   { return (w >> 6) & 31; }
inline u32 SH(u32 w)   { return (w >> 11) & 31; }
inline u32 MB(u32 w)   { return (w >> 6) & 31; }
inline u32 ME(u32 w)   { return (w >> 1) & 31; }
inline u32 XO10(u32 w) { return (w >> 1) & 0x3FF; }
inline u32 XO5(u32 w)  { return (w >> 1) & 0x1F; }
inline bool Rc(u32 w)  { return w & 1; }
inline bool OE(u32 w)  { return (w >> 10) & 1; }
inline s32 SIMM(u32 w) { return s16(w & 0xFFFF); }
inline u32 UIMM(u32 w) { return w & 0xFFFF; }

// A comma-separated list of hex guest addresses from an environment variable,
// which is how every address-triggered diagnostic here is configured.
std::vector<GuestAddr> addressList(const char* var) {
  std::vector<GuestAddr> out;
  const char* v = std::getenv(var);
  for (const char* p = v; p && *p;) {
    char* end = nullptr;
    const unsigned long a = std::strtoul(p, &end, 0);
    if (end == p) break;
    if (a) out.push_back(GuestAddr(a));
    p = (*end == ',') ? end + 1 : end;
  }
  return out;
}
inline u32 BO(u32 w)   { return (w >> 21) & 31; }
inline u32 BI(u32 w)   { return (w >> 16) & 31; }
inline u32 CRFD(u32 w) { return (w >> 23) & 7; }
inline u32 CRFS(u32 w) { return (w >> 18) & 7; }
inline bool AA(u32 w)  { return (w >> 1) & 1; }
inline bool LK(u32 w)  { return w & 1; }

inline s32 signExtend(u32 v, int bits) {
  u32 m = 1u << (bits - 1);
  return s32((v ^ m) - m);
}

// The mask generated by the rotate-and-mask instructions: bits MB..ME set,
// inclusive, wrapping when MB > ME.
inline u32 rotMask(u32 mb, u32 me) {
  u32 begin = 0xFFFFFFFFu >> mb;
  u32 end = (me >= 31) ? 0xFFFFFFFFu : ~(0xFFFFFFFFu >> (me + 1));
  u32 m = begin & end;
  return (mb <= me) ? m : ~m;
}

inline u32 rotl32(u32 v, u32 n) {
  n &= 31;
  return n ? ((v << n) | (v >> (32 - n))) : v;
}

}  // namespace

u32 Interp::addCore(u32 a, u32 b, u32 carryIn, bool wantCa, bool oe, bool rc) {
  u64 wide = u64(a) + u64(b) + u64(carryIn);
  u32 r = u32(wide);
  if (wantCa) cpu_->setCa((wide >> 32) != 0);
  if (oe) {
    // Overflow is signed: both addends agree in sign and the result differs.
    bool ov = (~(a ^ b) & (a ^ r)) >> 31;
    setOv(ov);
  }
  if (rc) setCr0(r);
  return r;
}

void Interp::unimplemented(u32 op, const char* what) {
  std::ostringstream s;
  s << "unimplemented instruction " << what << " (0x" << std::hex << op
    << ") at 0x" << cpu_->pc;
  if (img_) {
    std::string sym = img_->symbolFor(cpu_->pc);
    if (!sym.empty()) s << " in " << sym;
  }
  halt(s.str());
}

void Interp::step() {
  PpcCpu& c = *cpu_;

  // A program counter inside the shim region is a native call, not code.
  if (Interp::isShimCode(c.pc)) {
    if (c.pc == kReturnSentinel) {
      halt("returned");
      return;
    }
    u32 index = (c.pc - kShimCodeBase) / 4;
    if (host_) host_(index, c);
    else { halt("native call with no host installed"); return; }
    if (c.halted) return;
    // A handler that switched context -- the Thread Manager's yield, say -- has
    // already installed the program counter it wants, so returning to the link
    // register would undo the switch.
    if (!c.branched_) c.pc = c.lr;
    c.branched_ = false;
    ++c.instructions;
    return;
  }

  // Watchpoints, for inspecting arguments at known entry points without
  // tracing everything. CYT_WATCH_PC holds one or more comma-separated hex
  // guest addresses; each hit prints the registers holding the first four
  // arguments, the link register, and the symbol the return address falls in,
  // which is enough to read a call sequence without a full trace.
  static const std::vector<GuestAddr> watch = addressList("CYT_WATCH_PC");
  if (!watch.empty() &&
      std::find(watch.begin(), watch.end(), c.pc) != watch.end()) {
    const std::string here = img_ ? img_->symbolFor(c.pc) : std::string();
    const std::string from = img_ ? img_->symbolFor(c.lr) : std::string();
    // The instruction count is printed so that a hit can be handed straight to
    // --trace-from, which is how a watchpoint turns into a full Toolbox trace
    // of whatever the function goes on to do.
    std::fprintf(stderr,
                 "  [watch] n=%llu %08x %-40s r3=%08x r4=%08x r5=%08x r6=%08x "
                 "from %s\n",
                 (unsigned long long)c.instructions, c.pc, here.c_str(),
                 c.gpr[3], c.gpr[4], c.gpr[5], c.gpr[6],
                 from.empty() ? "?" : from.c_str());
  }

  // Arming call tracing at an address, rather than at an instruction count:
  // counts are not reproducible between runs, because the game's delay loops
  // spin on TickCount, but "the moment control reaches this function" is.
  static const std::vector<GuestAddr> armAt =
      addressList("CYT_TRACE_CALLS_FROM_PC");
  if (armTrace_ && !armAt.empty() &&
      std::find(armAt.begin(), armAt.end(), c.pc) != armAt.end()) {
    std::fprintf(stderr, "  [trace] arming Toolbox call tracing at %08x %s\n",
                 c.pc, img_ ? img_->symbolFor(c.pc).c_str() : "");
    armTrace_();
    armTrace_ = nullptr;
  }

  // A trace narrowed to one address range, which is how a single function's
  // control flow is read without the cost -- or the volume -- of tracing
  // everything. CYT_TRACE_RANGE holds "lo:hi" as hex guest addresses.
  static const std::pair<GuestAddr, GuestAddr> traceRange = [] {
    const char* v = std::getenv("CYT_TRACE_RANGE");
    if (!v) return std::pair<GuestAddr, GuestAddr>{0, 0};
    char* end = nullptr;
    const GuestAddr lo = GuestAddr(std::strtoul(v, &end, 0));
    const GuestAddr hi =
        (end && *end == ':') ? GuestAddr(std::strtoul(end + 1, nullptr, 0)) : lo;
    return std::pair<GuestAddr, GuestAddr>{lo, hi};
  }();
  if (traceRange.first && c.pc >= traceRange.first && c.pc <= traceRange.second) {
    const std::string sym = img_ ? img_->symbolFor(c.pc) : std::string();
    std::fprintf(stderr, "  [range] %08x %08x %-40s r3=%08x r4=%08x\n", c.pc,
                 mem_->r32(c.pc), sym.c_str(), c.gpr[3], c.gpr[4]);
  }

  u32 op = mem_->r32(c.pc);
  if (trace_) {
    std::string sym = img_ ? img_->symbolFor(c.pc) : std::string();
    std::fprintf(stderr, "%08x  %08x  %-28s r3=%08x r4=%08x r1=%08x\n", c.pc, op,
                 sym.c_str(), c.gpr[3], c.gpr[4], c.gpr[1]);
  }
  u32 next = c.pc + 4;
  execute(op);
  if (!c.branched_) c.pc = next;
  c.branched_ = false;
  ++c.instructions;
}

u64 Interp::run(u64 budget) {
  u64 start = cpu_->instructions;
  while (!cpu_->halted) {
    if (limit_ && cpu_->instructions >= limit_) {
      halt("budget exhausted");
      break;
    }
    step();
    if (budget && cpu_->instructions - start >= budget) break;
  }
  return cpu_->instructions - start;
}

u32 Interp::callTVector(GuestAddr tvector, u64 budget) {
  PpcCpu& c = *cpu_;
  c.gpr[2] = mem_->r32(tvector + 4);
  c.pc = mem_->r32(tvector + 0);
  c.lr = kReturnSentinel;
  c.halted = false;
  c.haltReason.clear();
  run(budget);
  return c.gpr[3];
}

u32 Interp::callPpc(GuestAddr code, GuestAddr toc,
                    const std::vector<u32>& args, u64 budget) {
  PpcCpu saved = *cpu_;
  PpcCpu& c = *cpu_;

  // Leave the caller's frame untouched and build a new one well below it, with
  // room for the callee's parameter save area and any arguments past r10.
  GuestAddr sp = (saved.gpr[1] - 512 - u32(args.size()) * 4) & ~15u;
  mem_->w32(sp, saved.gpr[1]);
  c.gpr[1] = sp;
  if (toc) c.gpr[2] = toc;
  for (size_t i = 0; i < args.size(); ++i) {
    if (i < 8) c.gpr[3 + i] = args[i];
    else mem_->w32(sp + 56 + u32(i) * 4, args[i]);
  }
  c.pc = code;
  c.lr = kReturnSentinel;
  c.halted = false;
  c.haltReason.clear();
  run(budget);

  u32 result = c.gpr[3];
  const bool clean = c.halted && c.haltReason == "returned";
  const std::string why = c.haltReason;
  u64 spent = c.instructions;
  *cpu_ = saved;
  cpu_->instructions = spent;
  if (!clean) {
    // A callee that never returned means the guest is in an unknown state; say
    // so rather than letting the caller resume on a half-executed callback.
    // Whatever stopped it -- an exhausted budget, an unknown opcode -- is more
    // informative than the fact that the call did not come back, so it is kept.
    char at[32];
    std::snprintf(at, sizeof at, "0x%08x", code);
    halt(why.empty() ? "nested call to " + std::string(at) + " did not return"
                     : why + " (inside a nested call to " + at + ")");
  }
  return result;
}

std::string Interp::disasmOne(GuestAddr pc) const {
  char buf[64];
  std::snprintf(buf, sizeof buf, "%08x", mem_->r32(pc));
  return buf;
}

void Interp::execute(u32 w) {
  PpcCpu& c = *cpu_;
  Mem& m = *mem_;
  u32* g = c.gpr;

  auto branchTo = [&](u32 target, bool link, u32 retAddr) {
    if (link) c.lr = retAddr;
    c.pc = target & ~3u;
    c.branched_ = true;
  };

  switch (OPCD(w)) {
    // ---- branches ---------------------------------------------------------
    case 18: {                                   // b, ba, bl, bla
      s32 li = signExtend((w >> 2) & 0xFFFFFF, 24) * 4;
      u32 target = AA(w) ? u32(li) : c.pc + u32(li);
      branchTo(target, LK(w), c.pc + 4);
      break;
    }
    case 16: {                                   // bc: conditional branch
      s32 bd = signExtend((w >> 2) & 0x3FFF, 14) * 4;
      u32 target = AA(w) ? u32(bd) : c.pc + u32(bd);
      u32 bo = BO(w);
      bool ctrOk = true, condOk = true;
      if (!(bo & 4)) {                           // decrement and test CTR
        --c.ctr;
        ctrOk = (bo & 2) ? (c.ctr == 0) : (c.ctr != 0);
      }
      if (!(bo & 16)) condOk = c.crBit(BI(w)) == ((bo >> 3) & 1);
      if (ctrOk && condOk) branchTo(target, LK(w), c.pc + 4);
      else if (LK(w)) c.lr = c.pc + 4;
      break;
    }
    case 19:                                     // bclr / bcctr / isync
      switch (XO10(w)) {
        case 16: {                               // bclr (blr)
          u32 bo = BO(w);
          bool ctrOk = true, condOk = true;
          if (!(bo & 4)) {
            --c.ctr;
            ctrOk = (bo & 2) ? (c.ctr == 0) : (c.ctr != 0);
          }
          if (!(bo & 16)) condOk = c.crBit(BI(w)) == ((bo >> 3) & 1);
          u32 target = c.lr;
          if (ctrOk && condOk) branchTo(target, LK(w), c.pc + 4);
          else if (LK(w)) c.lr = c.pc + 4;
          break;
        }
        case 528: {                              // bcctr (bctr, bctrl)
          u32 bo = BO(w);
          bool condOk = (bo & 16) || c.crBit(BI(w)) == ((bo >> 3) & 1);
          u32 target = c.ctr;
          if (condOk) branchTo(target, LK(w), c.pc + 4);
          else if (LK(w)) c.lr = c.pc + 4;
          break;
        }
        case 150: break;                         // isync: no-op here
        case 0:   {                              // mcrf
          c.setCrField(CRFD(w), c.crField(CRFS(w)));
          break;
        }
        case 33: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                   c.setCrBit((w >> 21) & 31, !(a | b)); break; }  // crnor
        case 129: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, a & !b); break; }   // crandc
        case 193: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, a ^ b); break; }    // crxor
        case 225: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, !(a & b)); break; } // crnand
        case 257: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, a & b); break; }    // crand
        case 289: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, !(a ^ b)); break; } // creqv
        case 417: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, a | !b); break; }   // crorc
        case 449: { u32 b = c.crBit(BI(w)), a = c.crBit((w >> 21) & 31);
                    c.setCrBit((w >> 21) & 31, a | b); break; }    // cror
        default: unimplemented(w, "opcode 19 extended"); break;
      }
      break;

    // ---- integer arithmetic with immediates --------------------------------
    case 7:  g[rD(w)] = u32(s32(g[rA(w)]) * SIMM(w)); break;      // mulli
    case 8: {                                                     // subfic
      u32 a = g[rA(w)], b = u32(SIMM(w));
      u64 wide = u64(~a) + u64(b) + 1;
      g[rD(w)] = u32(wide);
      c.setCa((wide >> 32) != 0);
      break;
    }
    case 10: {                                                    // cmpli
      u32 a = g[rA(w)], b = UIMM(w);
      u32 f = a < b ? 8u : (a > b ? 4u : 2u);
      if (c.xer & kXerSo) f |= 1u;
      c.setCrField(CRFD(w), f);
      break;
    }
    case 11: {                                                    // cmpi
      s32 a = s32(g[rA(w)]), b = SIMM(w);
      u32 f = a < b ? 8u : (a > b ? 4u : 2u);
      if (c.xer & kXerSo) f |= 1u;
      c.setCrField(CRFD(w), f);
      break;
    }
    case 12: g[rD(w)] = addCore(g[rA(w)], u32(SIMM(w)), 0, true, false, false);
             break;                                               // addic
    case 13: g[rD(w)] = addCore(g[rA(w)], u32(SIMM(w)), 0, true, false, true);
             break;                                               // addic.
    case 14: g[rD(w)] = (rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)); break;  // addi
    case 15: g[rD(w)] = (rA(w) ? g[rA(w)] : 0) + (UIMM(w) << 16); break; // addis

    // ---- logical with immediates ------------------------------------------
    case 24: g[rA(w)] = g[rS(w)] | UIMM(w); break;                // ori
    case 25: g[rA(w)] = g[rS(w)] | (UIMM(w) << 16); break;        // oris
    case 26: g[rA(w)] = g[rS(w)] ^ UIMM(w); break;                // xori
    case 27: g[rA(w)] = g[rS(w)] ^ (UIMM(w) << 16); break;        // xoris
    case 28: g[rA(w)] = g[rS(w)] & UIMM(w); setCr0(g[rA(w)]); break;  // andi.
    case 29: g[rA(w)] = g[rS(w)] & (UIMM(w) << 16); setCr0(g[rA(w)]);
             break;                                               // andis.

    // ---- rotate and mask --------------------------------------------------
    case 20: {                                                    // rlwimi
      u32 r = rotl32(g[rS(w)], SH(w));
      u32 msk = rotMask(MB(w), ME(w));
      g[rA(w)] = (r & msk) | (g[rA(w)] & ~msk);
      if (Rc(w)) setCr0(g[rA(w)]);
      break;
    }
    case 21: {                                                    // rlwinm
      g[rA(w)] = rotl32(g[rS(w)], SH(w)) & rotMask(MB(w), ME(w));
      if (Rc(w)) setCr0(g[rA(w)]);
      break;
    }
    case 23: {                                                    // rlwnm
      g[rA(w)] = rotl32(g[rS(w)], g[rB(w)] & 31) & rotMask(MB(w), ME(w));
      if (Rc(w)) setCr0(g[rA(w)]);
      break;
    }

    // ---- loads and stores with displacement -------------------------------
    case 32: g[rD(w)] = m.r32((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))); break;
    case 33: { u32 a = g[rA(w)] + u32(SIMM(w)); g[rD(w)] = m.r32(a); g[rA(w)] = a; break; }
    case 34: g[rD(w)] = m.r8((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))); break;
    case 35: { u32 a = g[rA(w)] + u32(SIMM(w)); g[rD(w)] = m.r8(a); g[rA(w)] = a; break; }
    case 36: m.w32((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)), g[rS(w)]); break;
    case 37: { u32 a = g[rA(w)] + u32(SIMM(w)); m.w32(a, g[rS(w)]); g[rA(w)] = a; break; }
    case 38: m.w8((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)), u8(g[rS(w)])); break;
    case 39: { u32 a = g[rA(w)] + u32(SIMM(w)); m.w8(a, u8(g[rS(w)])); g[rA(w)] = a; break; }
    case 40: g[rD(w)] = m.r16((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))); break;
    case 41: { u32 a = g[rA(w)] + u32(SIMM(w)); g[rD(w)] = m.r16(a); g[rA(w)] = a; break; }
    case 42: g[rD(w)] = u32(s32(m.rs16((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))))); break;
    case 43: { u32 a = g[rA(w)] + u32(SIMM(w)); g[rD(w)] = u32(s32(m.rs16(a)));
               g[rA(w)] = a; break; }
    case 44: m.w16((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)), u16(g[rS(w)])); break;
    case 45: { u32 a = g[rA(w)] + u32(SIMM(w)); m.w16(a, u16(g[rS(w)])); g[rA(w)] = a; break; }
    case 46: {                                                    // lmw
      u32 a = (rA(w) ? g[rA(w)] : 0) + u32(SIMM(w));
      for (u32 r = rD(w); r < 32; ++r, a += 4) g[r] = m.r32(a);
      break;
    }
    case 47: {                                                    // stmw
      u32 a = (rA(w) ? g[rA(w)] : 0) + u32(SIMM(w));
      for (u32 r = rS(w); r < 32; ++r, a += 4) m.w32(a, g[r]);
      break;
    }

    // ---- floating point loads and stores ----------------------------------
    case 48: c.fpr[rD(w)] = m.rf32((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))); break;
    case 49: { u32 a = g[rA(w)] + u32(SIMM(w)); c.fpr[rD(w)] = m.rf32(a);
               g[rA(w)] = a; break; }
    case 50: c.fpr[rD(w)] = m.rf64((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w))); break;
    case 51: { u32 a = g[rA(w)] + u32(SIMM(w)); c.fpr[rD(w)] = m.rf64(a);
               g[rA(w)] = a; break; }
    case 52: m.wf32((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)), float(c.fpr[rS(w)])); break;
    case 53: { u32 a = g[rA(w)] + u32(SIMM(w)); m.wf32(a, float(c.fpr[rS(w)]));
               g[rA(w)] = a; break; }
    case 54: m.wf64((rA(w) ? g[rA(w)] : 0) + u32(SIMM(w)), c.fpr[rS(w)]); break;
    case 55: { u32 a = g[rA(w)] + u32(SIMM(w)); m.wf64(a, c.fpr[rS(w)]);
               g[rA(w)] = a; break; }

    // ---- the big extended-opcode group ------------------------------------
    case 31: {
      const bool oe = OE(w);
      const bool rc = Rc(w);
      u32 a = g[rA(w)], b = g[rB(w)];
      u32 ea = (rA(w) ? a : 0) + b;     // indexed effective address

      switch (XO10(w)) {
        case 0: {                                          // cmp
          s32 x = s32(a), y = s32(b);
          u32 f = x < y ? 8u : (x > y ? 4u : 2u);
          if (c.xer & kXerSo) f |= 1u;
          c.setCrField(CRFD(w), f);
          return;
        }
        case 32: {                                         // cmpl
          u32 f = a < b ? 8u : (a > b ? 4u : 2u);
          if (c.xer & kXerSo) f |= 1u;
          c.setCrField(CRFD(w), f);
          return;
        }
        case 4: return;                                    // tw: no traps here
        case 19: g[rD(w)] = c.cr; return;                  // mfcr
        case 144: {                                        // mtcrf
          u32 mask = 0;
          u32 crm = (w >> 12) & 0xFF;
          for (int i = 0; i < 8; ++i)
            if (crm & (0x80 >> i)) mask |= 0xFu << (28 - 4 * i);
          c.cr = (c.cr & ~mask) | (g[rS(w)] & mask);
          return;
        }
        case 339: {                                        // mfspr
          u32 raw = (w >> 11) & 0x3FF;
          u32 spr = ((raw & 0x1F) << 5) | ((raw >> 5) & 0x1F);
          switch (spr) {
            case 1: g[rD(w)] = c.xer; break;
            case 8: g[rD(w)] = c.lr; break;
            case 9: g[rD(w)] = c.ctr; break;
            default: g[rD(w)] = 0; break;
          }
          return;
        }
        case 467: {                                        // mtspr
          u32 raw = (w >> 11) & 0x3FF;
          u32 spr = ((raw & 0x1F) << 5) | ((raw >> 5) & 0x1F);
          switch (spr) {
            case 1: c.xer = g[rS(w)]; break;
            case 8: c.lr = g[rS(w)]; break;
            case 9: c.ctr = g[rS(w)]; break;
            default: break;
          }
          return;
        }
        case 371: g[rD(w)] = u32(c.instructions); return;   // mftb
        case 512: {                                        // mcrxr
          c.setCrField(CRFD(w), (c.xer >> 28) & 0xF);
          c.xer &= 0x0FFFFFFF;
          return;
        }
        // Cache and synchronisation hints have no meaning without a cache.
        case 54: case 86: case 246: case 278: case 454: case 470:
        case 598: case 854: case 982: case 1014:
          return;
        case 20: g[rD(w)] = m.r32(ea); return;             // lwarx
        case 150: m.w32(ea, g[rS(w)]); c.setCrField(0, 2); return;  // stwcx.

        // Indexed loads and stores.
        case 23:  g[rD(w)] = m.r32(ea); return;                     // lwzx
        case 55:  g[rD(w)] = m.r32(ea); g[rA(w)] = ea; return;      // lwzux
        case 87:  g[rD(w)] = m.r8(ea); return;                      // lbzx
        case 119: g[rD(w)] = m.r8(ea); g[rA(w)] = ea; return;       // lbzux
        case 279: g[rD(w)] = m.r16(ea); return;                     // lhzx
        case 311: g[rD(w)] = m.r16(ea); g[rA(w)] = ea; return;      // lhzux
        case 343: g[rD(w)] = u32(s32(m.rs16(ea))); return;          // lhax
        case 375: g[rD(w)] = u32(s32(m.rs16(ea))); g[rA(w)] = ea; return;  // lhaux
        case 151: m.w32(ea, g[rS(w)]); return;                      // stwx
        case 183: m.w32(ea, g[rS(w)]); g[rA(w)] = ea; return;       // stwux
        case 215: m.w8(ea, u8(g[rS(w)])); return;                   // stbx
        case 247: m.w8(ea, u8(g[rS(w)])); g[rA(w)] = ea; return;     // stbux
        case 407: m.w16(ea, u16(g[rS(w)])); return;                 // sthx
        case 439: m.w16(ea, u16(g[rS(w)])); g[rA(w)] = ea; return;   // sthux
        case 534: g[rD(w)] = __builtin_bswap32(m.r32(ea)); return;  // lwbrx
        case 662: m.w32(ea, __builtin_bswap32(g[rS(w)])); return;   // stwbrx
        case 790: g[rD(w)] = __builtin_bswap16(u16(m.r16(ea))); return;  // lhbrx
        case 918: m.w16(ea, __builtin_bswap16(u16(g[rS(w)]))); return;   // sthbrx
        case 535: c.fpr[rD(w)] = m.rf32(ea); return;                // lfsx
        case 567: c.fpr[rD(w)] = m.rf32(ea); g[rA(w)] = ea; return; // lfsux
        case 599: c.fpr[rD(w)] = m.rf64(ea); return;                // lfdx
        case 631: c.fpr[rD(w)] = m.rf64(ea); g[rA(w)] = ea; return; // lfdux
        case 663: m.wf32(ea, float(c.fpr[rS(w)])); return;          // stfsx
        case 695: m.wf32(ea, float(c.fpr[rS(w)])); g[rA(w)] = ea; return;  // stfsux
        case 727: m.wf64(ea, c.fpr[rS(w)]); return;                 // stfdx
        case 759: m.wf64(ea, c.fpr[rS(w)]); g[rA(w)] = ea; return;  // stfdux
        case 983: {                                                 // stfiwx
          u64 bits;
          std::memcpy(&bits, &c.fpr[rS(w)], 8);
          m.w32(ea, u32(bits));
          return;
        }
        case 597: {                                                 // lswi
          u32 n = SH(w) ? SH(w) : 32;
          u32 addr = rA(w) ? a : 0;
          u32 r = rD(w), shift = 24;
          g[r] = 0;
          for (u32 i = 0; i < n; ++i) {
            g[r] |= u32(m.r8(addr + i)) << shift;
            if (shift == 0) { shift = 24; r = (r + 1) & 31; g[r] = 0; }
            else shift -= 8;
          }
          return;
        }
        case 725: {                                                 // stswi
          u32 n = SH(w) ? SH(w) : 32;
          u32 addr = rA(w) ? a : 0;
          u32 r = rS(w), shift = 24;
          for (u32 i = 0; i < n; ++i) {
            m.w8(addr + i, u8(g[r] >> shift));
            if (shift == 0) { shift = 24; r = (r + 1) & 31; }
            else shift -= 8;
          }
          return;
        }
        // Logical, shift and sign-extend forms. These have no overflow-enable
        // bit, so they are dispatched on the full ten-bit opcode, and they
        // write rA from rS -- the opposite direction to the arithmetic forms.
        case 28:  g[rA(w)] = g[rS(w)] & b;    if (rc) setCr0(g[rA(w)]); return; // and
        case 60:  g[rA(w)] = g[rS(w)] & ~b;   if (rc) setCr0(g[rA(w)]); return; // andc
        case 444: g[rA(w)] = g[rS(w)] | b;    if (rc) setCr0(g[rA(w)]); return; // or
        case 412: g[rA(w)] = g[rS(w)] | ~b;   if (rc) setCr0(g[rA(w)]); return; // orc
        case 316: g[rA(w)] = g[rS(w)] ^ b;    if (rc) setCr0(g[rA(w)]); return; // xor
        case 476: g[rA(w)] = ~(g[rS(w)] & b); if (rc) setCr0(g[rA(w)]); return; // nand
        case 124: g[rA(w)] = ~(g[rS(w)] | b); if (rc) setCr0(g[rA(w)]); return; // nor
        case 284: g[rA(w)] = ~(g[rS(w)] ^ b); if (rc) setCr0(g[rA(w)]); return; // eqv
        case 954: g[rA(w)] = u32(s32(s8(g[rS(w)])));
                  if (rc) setCr0(g[rA(w)]); return;                    // extsb
        case 922: g[rA(w)] = u32(s32(s16(g[rS(w)])));
                  if (rc) setCr0(g[rA(w)]); return;                    // extsh
        case 26: {                                                     // cntlzw
          u32 v = g[rS(w)];
          g[rA(w)] = v ? u32(__builtin_clz(v)) : 32u;
          if (rc) setCr0(g[rA(w)]);
          return;
        }
        case 24: {                                                     // slw
          u32 sh = b & 63;
          g[rA(w)] = (sh < 32) ? (g[rS(w)] << sh) : 0;
          if (rc) setCr0(g[rA(w)]);
          return;
        }
        case 536: {                                                    // srw
          u32 sh = b & 63;
          g[rA(w)] = (sh < 32) ? (g[rS(w)] >> sh) : 0;
          if (rc) setCr0(g[rA(w)]);
          return;
        }
        case 792: {                                                    // sraw
          u32 sh = b & 63;
          s32 v = s32(g[rS(w)]);
          if (sh >= 32) {
            g[rA(w)] = u32(v >> 31);
            c.setCa(v < 0);
          } else {
            g[rA(w)] = u32(v >> sh);
            c.setCa(v < 0 && (u32(v) & ((1u << sh) - 1)) != 0);
          }
          if (rc) setCr0(g[rA(w)]);
          return;
        }
        case 824: {                            // srawi: SH is a literal here
          u32 sh = SH(w);
          s32 v = s32(g[rS(w)]);
          g[rA(w)] = u32(v >> sh);
          c.setCa(v < 0 && sh && (u32(v) & ((1u << sh) - 1)) != 0);
          if (rc) setCr0(g[rA(w)]);
          return;
        }
        default: break;
      }

      // Arithmetic forms, where bit 9 of the extended field is overflow-enable.
      switch (XO10(w) & 0x1FF) {
        case 266: g[rD(w)] = addCore(a, b, 0, false, oe, rc); return;   // add
        case 10:  g[rD(w)] = addCore(a, b, 0, true, oe, rc); return;    // addc
        case 138: g[rD(w)] = addCore(a, b, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // adde
        case 202: g[rD(w)] = addCore(a, 0, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // addze
        case 234: g[rD(w)] = addCore(a, 0xFFFFFFFFu, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // addme
        case 40:  g[rD(w)] = addCore(~a, b, 1, false, oe, rc); return;  // subf
        case 8:   g[rD(w)] = addCore(~a, b, 1, true, oe, rc); return;   // subfc
        case 136: g[rD(w)] = addCore(~a, b, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // subfe
        case 200: g[rD(w)] = addCore(~a, 0, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // subfze
        case 232: g[rD(w)] = addCore(~a, 0xFFFFFFFFu, c.ca() ? 1 : 0, true, oe, rc);
                  return;                                              // subfme
        case 104: {                                                    // neg
          g[rD(w)] = u32(-s64(s32(a)));
          if (oe) setOv(a == 0x80000000u);
          if (rc) setCr0(g[rD(w)]);
          return;
        }
        case 235: {                                                    // mullw
          s64 p = s64(s32(a)) * s64(s32(b));
          g[rD(w)] = u32(p);
          if (oe) setOv(p != s64(s32(u32(p))));
          if (rc) setCr0(g[rD(w)]);
          return;
        }
        case 75:  g[rD(w)] = u32((s64(s32(a)) * s64(s32(b))) >> 32);
                  if (rc) setCr0(g[rD(w)]); return;                    // mulhw
        case 11:  g[rD(w)] = u32((u64(a) * u64(b)) >> 32);
                  if (rc) setCr0(g[rD(w)]); return;                    // mulhwu
        case 491: {                                                    // divw
          s32 x = s32(a), y = s32(b);
          if (y == 0 || (x == INT32_MIN && y == -1)) {
            g[rD(w)] = (x < 0) ? 0xFFFFFFFFu : 0;
            if (oe) setOv(true);
          } else {
            g[rD(w)] = u32(x / y);
            if (oe) setOv(false);
          }
          if (rc) setCr0(g[rD(w)]);
          return;
        }
        case 459: {                                                    // divwu
          if (b == 0) { g[rD(w)] = 0; if (oe) setOv(true); }
          else { g[rD(w)] = a / b; if (oe) setOv(false); }
          if (rc) setCr0(g[rD(w)]);
          return;
        }
        default: break;
      }
      unimplemented(w, "opcode 31 extended");
      break;
    }

    // ---- floating point ---------------------------------------------------
    case 59: case 63: {
      const bool single = OPCD(w) == 59;
      const bool rc = Rc(w);
      double* f = c.fpr;
      auto finish = [&](u32 d, double v) {
        f[d] = single ? double(float(v)) : v;
        // Rc updates CR1 (FP exception summary), which no compiler-generated
        // code here reads. Deliberately left alone: writing CR0 instead would
        // clobber the integer compare results the branch logic depends on.
        (void)rc;
      };
      switch (XO5(w)) {                     // A-form: XO is five bits
        case 18: finish(rD(w), f[rA(w)] / f[rB(w)]); return;      // fdiv
        case 20: finish(rD(w), f[rA(w)] - f[rB(w)]); return;      // fsub
        case 21: finish(rD(w), f[rA(w)] + f[rB(w)]); return;      // fadd
        case 22: finish(rD(w), std::sqrt(f[rA(w)])); return;      // fsqrt
        case 24: finish(rD(w), 1.0 / f[rB(w)]); return;           // fres
        case 25: finish(rD(w), f[rA(w)] * f[rC(w)]); return;      // fmul
        case 26: finish(rD(w), 1.0 / std::sqrt(f[rB(w)])); return; // frsqrte
        case 28: finish(rD(w), f[rA(w)] * f[rC(w)] - f[rB(w)]); return;  // fmsub
        case 29: finish(rD(w), f[rA(w)] * f[rC(w)] + f[rB(w)]); return;  // fmadd
        case 30: finish(rD(w), -(f[rA(w)] * f[rC(w)] - f[rB(w)])); return; // fnmsub
        case 31: finish(rD(w), -(f[rA(w)] * f[rC(w)] + f[rB(w)])); return; // fnmadd
        case 23: finish(rD(w), (f[rA(w)] >= 0.0) ? f[rC(w)] : f[rB(w)]); return;  // fsel
        default: break;
      }
      switch (XO10(w)) {                    // X-form: XO is ten bits
        case 0: case 32: {                                   // fcmpu / fcmpo
          double x = f[rA(w)], y = f[rB(w)];
          u32 fl = std::isunordered(x, y) ? 1u
                 : (x < y ? 8u : (x > y ? 4u : 2u));
          c.setCrField(CRFD(w), fl);
          return;
        }
        case 12: f[rD(w)] = double(float(f[rB(w)])); return;  // frsp
        case 14: case 15: {                                   // fctiw / fctiwz
          double v = f[rB(w)];
          s32 i = (XO10(w) == 15) ? s32(v) : s32(std::nearbyint(v));
          u64 bits = u64(u32(i));
          std::memcpy(&f[rD(w)], &bits, 8);
          return;
        }
        case 40: f[rD(w)] = -f[rB(w)]; return;                // fneg
        case 72: f[rD(w)] = f[rB(w)]; return;                 // fmr
        case 136: f[rD(w)] = -std::fabs(f[rB(w)]); return;    // fnabs
        case 264: f[rD(w)] = std::fabs(f[rB(w)]); return;     // fabs
        case 583: { u64 b = c.fpscr; std::memcpy(&f[rD(w)], &b, 8); return; }  // mffs
        case 711: return;                                     // mtfsf
        case 64: c.setCrField(CRFD(w), (c.fpscr >> (28 - 4 * CRFS(w))) & 0xF);
                 return;                                      // mcrfs
        case 70: case 134: case 38: return;   // mtfsb0/mtfsfi/mtfsb1: no effect
        default: break;
      }
      unimplemented(w, "floating point");
      break;
    }

    case 17: unimplemented(w, "sc (system call)"); break;
    default: unimplemented(w, "primary opcode"); break;
  }
}

}  // namespace cyt
